# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorikeet', '0004_auto_20161220_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCard',
            fields=[
                ('paymentmethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lorikeet.PaymentMethod')),
                ('card_token', models.CharField(max_length=30)),
                ('customer_token', models.CharField(max_length=30)),
            ],
            bases=('lorikeet.paymentmethod',),
        ),
    ]
