# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_stripepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecard',
            old_name='card_token',
            new_name='card_id',
        ),
        migrations.RenameField(
            model_name='stripecard',
            old_name='customer_token',
            new_name='customer_id',
        ),
    ]
