# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-04 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorikeet', '0013_auto_20170307_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarShipItOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='starshipit_order', to='lorikeet.Order')),
            ],
        ),
    ]
