# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-10 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lorikeet', '0005_cart_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyLineItem',
            fields=[
                ('lineitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lorikeet.LineItem')),
                ('quantity', models.PositiveSmallIntegerField()),
            ],
            bases=('lorikeet.lineitem',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='mylineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Product'),
        ),
    ]
