# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lorikeet", "0005_cart_payment_method"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AustralianDeliveryAddress",
            fields=[
                (
                    "deliveryaddress_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lorikeet.DeliveryAddress",
                    ),
                ),
                ("addressee", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("suburb", models.CharField(max_length=255)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NSW", "New South Wales"),
                            ("VIC", "Victoria"),
                            ("QLD", "Queensland"),
                            ("WA", "Western Australia"),
                            ("SA", "South Australia"),
                            ("TAS", "Tasmania"),
                            ("ACT", "Australian Capital Territory"),
                            ("NT", "Northern Territory"),
                        ],
                        max_length=3,
                    ),
                ),
                ("postcode", models.CharField(max_length=4)),
            ],
            bases=("lorikeet.deliveryaddress",),
        ),
        migrations.CreateModel(
            name="PipeCard",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lorikeet.PaymentMethod",
                    ),
                ),
                ("card_id", models.CharField(max_length=30)),
            ],
            bases=("lorikeet.paymentmethod",),
        ),
    ]
