# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lorikeet", "0008_auto_20170117_0453"),
        ("shop", "0002_australiandeliveryaddress_pipecard"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipePayment",
            fields=[
                (
                    "payment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lorikeet.Payment",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            bases=("lorikeet.payment",),
        ),
    ]
