# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-19 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lorikeet", "0015_adjustment"),
        ("shop", "0003_pipepayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartDiscount",
            fields=[
                (
                    "adjustment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lorikeet.Adjustment",
                    ),
                ),
                ("percentage", models.PositiveSmallIntegerField()),
            ],
            bases=("lorikeet.adjustment",),
        ),
    ]
