# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-20 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0002_auto_20161213_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('id',)},
        ),
    ]
