# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-04 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0004_auto_20161220_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lorikeet.PaymentMethod'),
        ),
    ]
