# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0005_cart_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
