# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-17 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0006_paymentmethod_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
