# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-06 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0010_order_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='total_when_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        # migrations.RunSQL(["""
        #     ALTER TABLE lorikeet_lineitem
        #     ADD CONSTRAINT total_when_charged_only_set_on_order CHECK (
        #         (order_id IS NULL AND total_when_charged IS NULL)
        #         OR (order_id IS NOT NULL AND total_when_charged IS NOT NULL)
        #     )
        # """], [])
    ]
