# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-07 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lorikeet', '0012_cart_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
