# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lorikeet", "0015_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="adjustment",
            name="total_when_charged",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
